require:
  - rubocop-rails

AllCops:
  Exclude:
    - "Gemfile"
    - "lib/templates/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "lib/templates/**/*"
    - "test/test_helper.rb"
    - "test/channels/application_cable/connection_test.rb"
  SuggestExtensions: false
  NewCops: enable

# pribate メソッドは、さらに 1 段インデントを下げる
#
#     ok: private
#           def foo()
#           end
#     ng: private
#         def foo()
#         end
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# メソッド呼び出しが複数行になった場合のインデントは、
<<<<<<< HEAD
# レシーバーの先頭から 1 段インデントを下げる
#
#     ok: foo = bar.method1()
#                 .method2()
#                 .method3()
#     ng: foo = bar.method1()
#           .method2()
#           .method3()
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
=======
# 直前行の先頭から 1 段インデントを下げる
#
#     ok: foo = bar.method1()
#           .method2()
#           .method3()
#     ng: foo = bar.method1()
#                 .method2()
#                 .method3()
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
>>>>>>> 4eeaec6c94afe53c2732e1637708b7d54c4f508b

# 空ブロックは 1 行にまとめる
#
#     ok: {}
#     ng: {
#         }
Lint/EmptyBlock:
  Enabled: false

<<<<<<< HEAD
=======
Style/Documentation:
  Enabled: false

>>>>>>> 4eeaec6c94afe53c2732e1637708b7d54c4f508b
# 空メソッドは 1 行にまとめない
#
#     ok: def foo(bar)
#         end
#     ng: def foo(bar); end
Style/EmptyMethod:
  EnforcedStyle: expanded

<<<<<<< HEAD
=======
Style/FrozenStringLiteralComment:
  Enabled: false

>>>>>>> 4eeaec6c94afe53c2732e1637708b7d54c4f508b
# 文字列リテラルはダブルクオーテーションで囲む
#
#     ok: "text"
#     ng: 'text'
Style/StringLiterals:
  EnforcedStyle: double_quotes

<<<<<<< HEAD

=======
>>>>>>> 4eeaec6c94afe53c2732e1637708b7d54c4f508b
